{% set name = "dectate" %}
{% set version = "0.14" %}
{% set sha256 = "56213abfe6ce31d6fe10dbf7a7cd94e07a26d5dc7cd0ae2e208c4ef2dbebb504" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - dectate

about:
  home: http://dectate.readthedocs.io
  license: BSD-3-Clause
  summary: 'A configuration engine for Python frameworks'
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    Dectate is a powerful configuration engine for Python frameworks.
  doc_url: http://dectate.readthedocs.org/
  dev_url: https://github.com/morepath/dectate
  
extra:
  recipe-maintainers:
    - stuertz
