{% set name = "dectate" %}
{% set version = "0.13" %}
{% set sha256 = "299a5d3d674d7cd095c8489331ecece22e5a567ee8a7636e8b57bbb220c568e4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - dectate

about:
  home: http://dectate.readthedocs.io
  license: BSD-3-Clause
  summary: 'A configuration engine for Python frameworks'
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    Dectate is a powerful configuration engine for Python frameworks.
  doc_url: http://dectate.readthedocs.org/
  dev_url: https://github.com/morepath/dectate
  
extra:
  recipe-maintainers:
    - stuertz
