travis:
  secure:
    BINSTAR_TOKEN: FfQEBpxTDRIVoX3Kx5Rx7CD0Lrkyb5Amk270oMneNFRBgSNflS74LDV9lPbPr/OYSomKTV1HP5mqeIB2TefDvV71lTBK8Pc3pF2X61hW52hBJrWb5ZJ7944l/H4Dmnqx9i/a20p5cz6kqE1xYKE3LBVzhqeDJRHqJLSwhObVlXxtOk/vVIi1a1csg4fnIS6nZ2Y57Ph/2YqBucl61OIFIcV0IjNa1EbjAEF0i34MoM6f48GhkgxtKKalfITBDWK58H2UgOkK8xik7ZDqdH/UvNXWf6Pa88tju2HGrEp8yafycVB/bPyK/8FIih96jB65hFeu2urwzvz8HTWonV3AjZyTBgv4HlCvKH5chc8cWanzcmzTmBCghroejkeFDm0mCIUi/EQr4ktLqYnPOHyUruW5ttBizlnlUEZtRSloGk+dKPH4rHL4FXIZEJckGcEvIrkcDJHwtdxaH9g1nCYi2kh/WN8+wT2YnhbzbCqBj5hMrpJDq9sNTC755bI/dp7zyFrFdTI6gjxzA88GnwCJ12PSHG2T+IDaNiep319RnBI6xNTef45VQOJWe6pNVBmaobKdqMwxZlfNLMPvFvXwpv5XsrSCF9QbIvkMkzCmrg/hHnH+18i9z7UaaDDkZa6UAj7LOqXjPmYEKl8iwn7Npg7BN4fOgSA54FQ9lQUoADI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
